sudo: required
services:
  - docker

before_script:
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi

script:
  - travis_wait 30 docker image build -t $DOCKER_USERNAME/nb-test-mini -f Dockerfile.mini.LL .
before_cache:
  - mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}' | grep continuumio | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'

cache:
  directories:
    - $HOME/docker

after_success:
  - docker push $DOCKER_USERNAME/nb-test-LL